language: ruby
rvm:
  - 2.5.0
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: gh-pages
before_install:
  - gem update --system
branches:
  only:
  - gh-pages
  - master
before_script:
 - chmod +x ./script/cibuild
script: ./script/cibuild
sudo: false
cache: bundler
