language: ruby
rvm:
  - 2.5.0
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master 
before_install:
  - gem update --system
branches:
  only:
    - master
before_script:
  - chmod +x ./script/cibuild
script: ./script/cibuild
sudo: false
