# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Global Math Project
email: info@globalmathrproject.org
description: >- # this means to ignore newlines until "baseurl:"
  Join more than 2 million students, teachers, and friends that already have tried this astounding mathematical experience! See mathematics like you've never seen it before and take part in a global math conversation with your students.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.globalmathproject.org" # the base hostname & protocol for your site, e.g. http://example.com
type: Organization
twitter_username: GlobalMathProj
facebook_username: TheGlobalMathProject
youtube_username: TheGlobalMathProject

twitter:
  username: GlobalMathProj

facebook:
  app_id: 1071188719599489

encoding: utf-8
exclude: [vendor]

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/social-images/gmp-facebook-card.png
